// TOLF Configurator — shared language handling
(() => {
  const supported = ["en", "ru", "lv"];
  const requested = new URL(window.location.href).searchParams.get("lang");
  const saved = localStorage.getItem("tolf-language");
  const browser = (navigator.language || "en").toLowerCase();

  const language = supported.includes(requested)
    ? requested
    : supported.includes(saved)
      ? saved
      : browser.startsWith("ru")
        ? "ru"
        : browser.startsWith("lv")
          ? "lv"
          : "en";

  const text = {
    en: {
      rootTitle: "TOLF Configurator",
      backTolf: "‹ TOLF",
      backTolfAria: "TOLF home",
      rootSubtitle: "Generate network configuration profiles directly in your browser.",
      ikev2Description: "Create IKEv2 configuration files for Apple devices, Android strongSwan and Windows PowerShell (.ps1).",
      comingSoon: "Coming Soon",
      dnsDescription: "Create a system DNS configuration profile.",
      wifiDescription: "Create a Wi-Fi configuration profile.",
      privacyVerification: "Privacy & Verification",
      ikev2Title: "IKEv2 — TOLF Configurator",
      backConfigurator: "‹ TOLF Configurator",
      backConfiguratorAria: "Configurator home",
      ikev2Subtitle: "Create IKEv2 configuration files for Apple devices, strongSwan on Android, and Windows PowerShell.",
      privacyHeading: "Private by design",
      privacyLead: "Your VPN configuration stays on this device. Imported profiles, server addresses, usernames, passwords and generated configuration files are processed locally in your browser and are not uploaded to TOLF.",
      privacyNetwork: "The browser still makes ordinary requests required to load the website; your configuration values are not included in those requests.",
      privacyDetails: "Privacy details",
      privacyImported: "Imported files are read locally by your browser.",
      privacyCredentials: "Form values and passwords are not sent to the configurator server.",
      privacyGenerated: "Configuration files are generated locally on this device.",
      privacyContents: "TOLF does not receive the contents of generated profiles.",
      importExistingConfiguration: "Import Existing Configuration",
      importConfigurationHint: "Choose an existing profile or configuration file to load its settings into the configurator, edit them, and create a new file.",
      connection: "Connection",
      name: "Name",
      server: "Server",
      remoteId: "Remote ID",
      localId: "Local ID",
      optional: "Optional",
      authentication: "Authentication",
      username: "Username",
      password: "Password",
      advancedSettings: "Advanced Settings",
      ikeEncryption: "IKE Encryption",
      ikeIntegrity: "IKE Integrity",
      diffieHellman: "Diffie-Hellman",
      dpd: "Dead Peer Detection",
      appleOnly: "Apple only",
      none: "None",
      low: "Low",
      medium: "Medium",
      high: "High",
      pfs: "Perfect Forward Secrecy",
      redirects: "Redirects",
      internalSubnet: "IPv4/IPv6 Internal Subnet Attributes",
      onDemand: "On Demand",
      enableOnDemand: "Enable On Demand",
      alwaysOn: "Always On",
      alwaysOnHint: "Connect automatically on all networks.",
      defaultActions: "Default Actions",
      wifi: "Wi-Fi",
      cellular: "Cellular",
      ethernet: "Ethernet",
      connect: "Connect",
      disconnect: "Disconnect",
      ignore: "Ignore",
      additionalRules: "Additional Rules",
      wifiNetwork: "Wi-Fi Network",
      networkName: "Network name",
      removeRule: "Remove rule",
      addRule: "+ Add Rule",
      additionalRulesHint: "Additional rules are checked before the default actions.",
      installProfile: "Install Profile",
      shareProfile: "Share Profile",
      shareStrongSwan: "Share strongSwan",
      shareWindowsScript: "Share .ps1",
      saveWindowsScript: "Save .ps1",
      shareWindowsLauncher: "Share .cmd",
      saveWindowsLauncher: "Save .cmd",
      mobileconfigHelp: "Apple configuration profile for installing VPN settings on iPhone, iPad and Mac.",
      sswanHelp: "strongSwan profile file for importing VPN settings on Android.",
      ps1Help: "PowerShell script that creates the IKEv2 VPN connection in Windows.",
      cmdHelp: "Launcher file that starts the accompanying PowerShell script.",
      localProcessingNote: "Profile data and imported files are processed locally in your browser. Nothing is sent to the server.",
      disclaimer: "TOLF Configurator is an independent project and is not affiliated with, endorsed by, sponsored by, or supported by Apple Inc., Google LLC, or Microsoft Corporation. These companies are not responsible for this site or for configuration profiles generated by it. Apple, iPhone, iPad and iOS are trademarks of Apple Inc. Android and Google are trademarks of Google LLC. Windows and PowerShell are trademarks of Microsoft Corporation."
    },
    ru: {
      rootTitle: "TOLF Configurator",
      backTolf: "‹ TOLF",
      backTolfAria: "На главную TOLF",
      rootSubtitle: "Создавайте сетевые конфигурации прямо в браузере.",
      ikev2Description: "Создавайте IKEv2-конфигурации для устройств Apple, Android strongSwan и Windows PowerShell (.ps1).",
      comingSoon: "Скоро",
      dnsDescription: "Создавайте системные конфигурации DNS.",
      wifiDescription: "Создавайте профили конфигурации Wi-Fi.",
      privacyVerification: "Конфиденциальность и проверка",
      ikev2Title: "IKEv2 — TOLF Configurator",
      backConfigurator: "‹ TOLF Configurator",
      backConfiguratorAria: "На главную конфигуратора",
      ikev2Subtitle: "Создавайте конфигурации IKEv2 для устройств Apple, strongSwan на Android и Windows PowerShell.",
      privacyHeading: "Приватность заложена в основу",
      privacyLead: "Ваша VPN-конфигурация остаётся на этом устройстве. Импортированные профили, адреса серверов, имена пользователей, пароли и создаваемые конфигурационные файлы обрабатываются локально в браузере и не загружаются в TOLF.",
      privacyNetwork: "Браузер по-прежнему выполняет обычные запросы, необходимые для загрузки сайта; значения вашей конфигурации в эти запросы не включаются.",
      privacyDetails: "Подробнее о приватности",
      privacyImported: "Импортированные файлы читаются локально вашим браузером.",
      privacyCredentials: "Значения полей формы и пароли не отправляются на сервер конфигуратора.",
      privacyGenerated: "Конфигурационные файлы создаются локально на этом устройстве.",
      privacyContents: "TOLF не получает содержимое созданных профилей.",
      importExistingConfiguration: "Импортировать конфигурацию",
      importConfigurationHint: "Выберите существующий профиль или конфигурационный файл, чтобы загрузить его параметры в конфигуратор, изменить их и создать новый файл.",
      connection: "Подключение",
      name: "Название",
      server: "Сервер",
      remoteId: "Remote ID",
      localId: "Local ID",
      optional: "Необязательно",
      authentication: "Аутентификация",
      username: "Имя пользователя",
      password: "Пароль",
      advancedSettings: "Дополнительные настройки",
      ikeEncryption: "Шифрование IKE",
      ikeIntegrity: "Контроль целостности IKE",
      diffieHellman: "Diffie-Hellman",
      dpd: "Dead Peer Detection",
      appleOnly: "Только Apple",
      none: "Нет",
      low: "Low",
      medium: "Medium",
      high: "High",
      pfs: "Perfect Forward Secrecy",
      redirects: "Перенаправления",
      internalSubnet: "Атрибуты внутренней подсети IPv4/IPv6",
      onDemand: "On Demand",
      enableOnDemand: "Включить On Demand",
      alwaysOn: "Всегда включено",
      alwaysOnHint: "Подключаться автоматически во всех сетях.",
      defaultActions: "Действия по умолчанию",
      wifi: "Wi-Fi",
      cellular: "Сотовая сеть",
      ethernet: "Ethernet",
      connect: "Подключить",
      disconnect: "Отключить",
      ignore: "Игнорировать",
      additionalRules: "Дополнительные правила",
      wifiNetwork: "Сеть Wi-Fi",
      networkName: "Название сети",
      removeRule: "Удалить правило",
      addRule: "+ Добавить правило",
      additionalRulesHint: "Дополнительные правила проверяются перед действиями по умолчанию.",
      installProfile: "Установить профиль",
      shareProfile: "Поделиться профилем",
      shareStrongSwan: "Поделиться strongSwan",
      shareWindowsScript: "Поделиться .ps1",
      saveWindowsScript: "Сохранить .ps1",
      shareWindowsLauncher: "Поделиться .cmd",
      saveWindowsLauncher: "Сохранить .cmd",
      mobileconfigHelp: "Профиль конфигурации Apple для установки настроек VPN на iPhone, iPad и Mac.",
      sswanHelp: "Файл профиля strongSwan для импорта настроек VPN на Android.",
      ps1Help: "Сценарий PowerShell, который создаёт IKEv2-подключение VPN в Windows.",
      cmdHelp: "Файл запуска, который открывает соответствующий сценарий PowerShell.",
      localProcessingNote: "Данные профиля и импортированные файлы обрабатываются локально в браузере. На сервер ничего не отправляется.",
      disclaimer: "TOLF Configurator — независимый проект, не связанный с Apple Inc., Google LLC или Microsoft Corporation и не поддерживаемый ими. Эти компании не несут ответственности за этот сайт и создаваемые им конфигурационные профили. Apple, iPhone, iPad и iOS являются товарными знаками Apple Inc. Android и Google являются товарными знаками Google LLC. Windows и PowerShell являются товарными знаками Microsoft Corporation."
    },
    lv: {
      rootTitle: "TOLF Configurator",
      backTolf: "‹ TOLF",
      backTolfAria: "Uz TOLF sākumlapu",
      rootSubtitle: "Izveidojiet tīkla konfigurācijas tieši pārlūkprogrammā.",
      ikev2Description: "Izveidojiet IKEv2 konfigurācijas Apple ierīcēm, Android strongSwan un Windows PowerShell (.ps1).",
      comingSoon: "Drīzumā",
      dnsDescription: "Izveidojiet sistēmas DNS konfigurācijas profilu.",
      wifiDescription: "Izveidojiet Wi-Fi konfigurācijas profilu.",
      privacyVerification: "Privātums un pārbaude",
      ikev2Title: "IKEv2 — TOLF Configurator",
      backConfigurator: "‹ TOLF Configurator",
      backConfiguratorAria: "Uz konfiguratora sākumlapu",
      ikev2Subtitle: "Izveidojiet IKEv2 konfigurācijas Apple ierīcēm, strongSwan Android ierīcēs un Windows PowerShell.",
      privacyHeading: "Privātums pēc būtības",
      privacyLead: "Jūsu VPN konfigurācija paliek šajā ierīcē. Importētie profili, serveru adreses, lietotājvārdi, paroles un izveidotie konfigurācijas faili tiek apstrādāti lokāli pārlūkprogrammā un netiek augšupielādēti TOLF.",
      privacyNetwork: "Pārlūkprogramma joprojām veic parastos pieprasījumus, kas nepieciešami vietnes ielādei; jūsu konfigurācijas vērtības šajos pieprasījumos netiek iekļautas.",
      privacyDetails: "Plašāk par privātumu",
      privacyImported: "Importētie faili tiek nolasīti lokāli jūsu pārlūkprogrammā.",
      privacyCredentials: "Veidlapas vērtības un paroles netiek nosūtītas konfiguratora serverim.",
      privacyGenerated: "Konfigurācijas faili tiek izveidoti lokāli šajā ierīcē.",
      privacyContents: "TOLF nesaņem izveidoto profilu saturu.",
      importExistingConfiguration: "Importēt esošu konfigurāciju",
      importConfigurationHint: "Izvēlieties esošu profilu vai konfigurācijas failu, lai ielādētu tā parametrus konfiguratorā, tos mainītu un izveidotu jaunu failu.",
      connection: "Savienojums",
      name: "Nosaukums",
      server: "Serveris",
      remoteId: "Remote ID",
      localId: "Local ID",
      optional: "Neobligāti",
      authentication: "Autentifikācija",
      username: "Lietotājvārds",
      password: "Parole",
      advancedSettings: "Papildu iestatījumi",
      ikeEncryption: "IKE šifrēšana",
      ikeIntegrity: "IKE integritāte",
      diffieHellman: "Diffie-Hellman",
      dpd: "Dead Peer Detection",
      appleOnly: "Tikai Apple",
      none: "Nav",
      low: "Low",
      medium: "Medium",
      high: "High",
      pfs: "Perfect Forward Secrecy",
      redirects: "Pāradresācijas",
      internalSubnet: "IPv4/IPv6 iekšējā apakštīkla atribūti",
      onDemand: "On Demand",
      enableOnDemand: "Ieslēgt On Demand",
      alwaysOn: "Vienmēr ieslēgts",
      alwaysOnHint: "Automātiski izveidot savienojumu visos tīklos.",
      defaultActions: "Noklusējuma darbības",
      wifi: "Wi-Fi",
      cellular: "Mobilais tīkls",
      ethernet: "Ethernet",
      connect: "Savienot",
      disconnect: "Atvienot",
      ignore: "Ignorēt",
      additionalRules: "Papildu noteikumi",
      wifiNetwork: "Wi-Fi tīkls",
      networkName: "Tīkla nosaukums",
      removeRule: "Dzēst noteikumu",
      addRule: "+ Pievienot noteikumu",
      additionalRulesHint: "Papildu noteikumi tiek pārbaudīti pirms noklusējuma darbībām.",
      installProfile: "Instalēt profilu",
      shareProfile: "Kopīgot profilu",
      shareStrongSwan: "Kopīgot strongSwan",
      shareWindowsScript: "Kopīgot .ps1",
      saveWindowsScript: "Saglabāt .ps1",
      shareWindowsLauncher: "Kopīgot .cmd",
      saveWindowsLauncher: "Saglabāt .cmd",
      mobileconfigHelp: "Apple konfigurācijas profils VPN iestatījumu instalēšanai iPhone, iPad un Mac.",
      sswanHelp: "strongSwan profila fails VPN iestatījumu importēšanai Android ierīcē.",
      ps1Help: "PowerShell skripts, kas izveido IKEv2 VPN savienojumu sistēmā Windows.",
      cmdHelp: "Palaišanas fails, kas startē atbilstošo PowerShell skriptu.",
      localProcessingNote: "Profila dati un importētie faili tiek apstrādāti lokāli jūsu pārlūkprogrammā. Nekas netiek nosūtīts uz serveri.",
      disclaimer: "TOLF Configurator ir neatkarīgs projekts, kas nav saistīts ar Apple Inc., Google LLC vai Microsoft Corporation un nav šo uzņēmumu atbalstīts. Šie uzņēmumi nav atbildīgi par šo vietni vai tās izveidotajiem konfigurācijas profiliem. Apple, iPhone, iPad un iOS ir Apple Inc. preču zīmes. Android un Google ir Google LLC preču zīmes. Windows un PowerShell ir Microsoft Corporation preču zīmes."
    }
  };

  function installPrivacyPanel() {
    if (document.body?.dataset.page !== "ikev2") return;
    const hero = document.querySelector(".configurator-hero");
    if (!hero || document.querySelector(".privacy-assurance")) return;

    const panel = document.createElement("section");
    panel.className = "privacy-assurance";
    panel.setAttribute("aria-label", "Privacy");
    panel.innerHTML = `
      <div class="privacy-icon" aria-hidden="true">
        <svg viewBox="0 0 24 24" focusable="false">
          <path d="M12 2.5 19 5v5.6c0 4.8-2.9 8.8-7 10.9-4.1-2.1-7-6.1-7-10.9V5l7-2.5Zm0 2.1L7 6.4v4.2c0 3.8 2.1 7.1 5 8.9 2.9-1.8 5-5.1 5-8.9V6.4l-5-1.8Z"/>
        </svg>
      </div>
      <div class="privacy-copy">
        <h2 data-i18n="privacyHeading">Private by design</h2>
        <p data-i18n="privacyLead">Your VPN configuration stays on this device. Imported profiles, server addresses, usernames, passwords and generated configuration files are processed locally in your browser and are not uploaded to TOLF.</p>
        <details class="privacy-details">
          <summary data-i18n="privacyDetails">Privacy details</summary>
          <p class="privacy-network" data-i18n="privacyNetwork">The browser still makes ordinary requests required to load the website; your configuration values are not included in those requests.</p>
          <ul>
            <li data-i18n="privacyImported">Imported files are read locally by your browser.</li>
            <li data-i18n="privacyCredentials">Form values and passwords are not sent to the configurator server.</li>
            <li data-i18n="privacyGenerated">Configuration files are generated locally on this device.</li>
            <li data-i18n="privacyContents">TOLF does not receive the contents of generated profiles.</li>
          </ul>
        </details>
      </div>
    `;
    hero.insertAdjacentElement("afterend", panel);

    document.querySelector('.note[data-i18n="localProcessingNote"]')?.remove();

    const style = document.createElement("style");
    style.textContent = `
      .privacy-assurance {
        margin: 18px 0 0;
        padding: 16px 18px;
        display: grid;
        grid-template-columns: 34px minmax(0, 1fr);
        gap: 13px;
        border: 1px solid #d8d8dc;
        border-radius: 14px;
        background: rgba(255,255,255,.68);
      }
      .privacy-assurance + .configurator-tool-row {
        margin-top: 16px;
      }
      .privacy-icon {
        width: 34px;
        height: 34px;
        display: grid;
        place-items: center;
        border: 1px solid #d2d2d7;
        border-radius: 10px;
        background: #f1f1f3;
        color: #5f5f63;
      }
      .privacy-icon svg {
        width: 19px;
        height: 19px;
        fill: currentColor;
      }
      .privacy-copy h2 {
        margin: 1px 0 5px;
        font-size: 16px;
        line-height: 1.25;
        font-weight: 650;
        letter-spacing: -0.01em;
      }
      .privacy-copy p {
        margin: 0;
        color: #5f5f63;
        font-size: 14px;
        line-height: 1.45;
      }
      .privacy-copy .privacy-network {
        margin-top: 7px;
        color: #77777c;
        font-size: 13px;
      }
      .privacy-details {
        margin-top: 9px;
      }
      .privacy-details summary {
        width: fit-content;
        color: #5f5f63;
        font-size: 13px;
        font-weight: 600;
        cursor: pointer;
      }
      .privacy-details ul {
        margin: 9px 0 0;
        padding-left: 20px;
        color: #5f5f63;
        font-size: 13px;
        line-height: 1.5;
      }
      .privacy-details li + li {
        margin-top: 3px;
      }
      @media (max-width: 560px) {
        .privacy-assurance {
          grid-template-columns: 30px minmax(0, 1fr);
          gap: 11px;
          padding: 14px;
        }
        .privacy-icon {
          width: 30px;
          height: 30px;
          border-radius: 9px;
        }
        .privacy-icon svg {
          width: 17px;
          height: 17px;
        }
      }
      @media (prefers-color-scheme: dark) {
        .privacy-assurance {
          background: rgba(28,28,30,.72);
          border-color: #38383a;
        }
        .privacy-icon {
          background: #2c2c2e;
          border-color: #48484a;
          color: #b8b8bd;
        }
        .privacy-copy p,
        .privacy-details summary,
        .privacy-details ul {
          color: #b8b8bd;
        }
        .privacy-copy .privacy-network {
          color: #9a9aa0;
        }
      }
    `;
    document.head.appendChild(style);
  }

  function translateElements(root = document, lang = document.documentElement.lang) {
    const dictionary = text[lang] || text.en;
    root.querySelectorAll("[data-i18n]").forEach(element => {
      const key = element.dataset.i18n;
      if (Object.prototype.hasOwnProperty.call(dictionary, key)) {
        element.textContent = dictionary[key];
      }
    });

    root.querySelectorAll("[data-i18n-placeholder]").forEach(element => {
      const key = element.dataset.i18nPlaceholder;
      if (Object.prototype.hasOwnProperty.call(dictionary, key)) {
        element.placeholder = dictionary[key];
      }
    });

    root.querySelectorAll("[data-i18n-aria-label]").forEach(element => {
      const key = element.dataset.i18nAriaLabel;
      if (Object.prototype.hasOwnProperty.call(dictionary, key)) {
        element.setAttribute("aria-label", dictionary[key]);
      }
    });
  }

  window.tolfTranslateElements = translateElements;

  function applyLanguage(lang) {
    document.documentElement.lang = lang;
    localStorage.setItem("tolf-language", lang);

    translateElements(document, lang);

    document.querySelectorAll(".language button[data-lang]").forEach(button => {
      const active = button.dataset.lang === lang;
      button.classList.toggle("active", active);
      button.setAttribute("aria-pressed", active ? "true" : "false");
    });

    document.querySelectorAll("[data-lang-link]").forEach(link => {
      try {
        const target = new URL(link.getAttribute("href"), window.location.href);
        target.searchParams.set("lang", lang);
        link.href = target.href;
      } catch (_) {}
    });
  }

  document.querySelectorAll(".language button[data-lang]").forEach(button => {
    button.addEventListener("click", () => {
      const next = button.dataset.lang;
      if (!supported.includes(next) || next === document.documentElement.lang) {
        return;
      }

      localStorage.setItem("tolf-language", next);
      const target = new URL(window.location.href);
      target.searchParams.set("lang", next);
      applyLanguage(next);
      window.history.replaceState(null, "", target.href);
    });
  });

  installPrivacyPanel();
  applyLanguage(language);
})();