// TOLF Configurator — shared language handling
(() => {
  const supported = ["en", "ru", "lv"];
  const requested = new URL(window.location.href).searchParams.get("lang");
  const saved = localStorage.getItem("tolf-language");
  const browser = (navigator.language || "en").toLowerCase();

  const language = supported.includes(requested)
    ? requested
    : supported.includes(saved)
      ? saved
      : browser.startsWith("ru")
        ? "ru"
        : browser.startsWith("lv")
          ? "lv"
          : "en";

  const text = {
    en: {
      rootTitle: "TOLF Configurator",
      backTolf: "‹ TOLF",
      rootSubtitle: "Generate network configuration profiles directly in your browser.",
      ikev2Description: "Create IKEv2 configuration files for Apple devices, Android strongSwan and Windows PowerShell (.ps1).",
      comingSoon: "Coming Soon",
      dnsDescription: "Create a system DNS configuration profile.",
      wifiDescription: "Create a Wi-Fi configuration profile.",
      privacyVerification: "Privacy & Verification",
      ikev2Title: "IKEv2 — TOLF Configurator",
      backConfigurator: "‹ TOLF Configurator",
      ikev2Subtitle: "Create IKEv2 configuration files for Apple devices, strongSwan on Android, and Windows PowerShell.",
      importExistingConfiguration: "Import Existing Configuration",
      connection: "Connection",
      name: "Name",
      server: "Server",
      remoteId: "Remote ID",
      localId: "Local ID",
      optional: "Optional",
      authentication: "Authentication",
      username: "Username",
      password: "Password",
      advancedSettings: "Advanced Settings",
      ikeEncryption: "IKE Encryption",
      ikeIntegrity: "IKE Integrity",
      diffieHellman: "Diffie-Hellman",
      dpd: "Dead Peer Detection",
      appleOnly: "Apple only",
      none: "None",
      low: "Low",
      medium: "Medium",
      high: "High",
      pfs: "Perfect Forward Secrecy",
      redirects: "Redirects",
      internalSubnet: "IPv4/IPv6 Internal Subnet Attributes",
      onDemand: "On Demand",
      enableOnDemand: "Enable On Demand",
      alwaysOn: "Always On",
      alwaysOnHint: "Connect automatically on all networks.",
      defaultActions: "Default Actions",
      wifi: "Wi-Fi",
      cellular: "Cellular",
      ethernet: "Ethernet",
      connect: "Connect",
      disconnect: "Disconnect",
      ignore: "Ignore",
      additionalRules: "Additional Rules",
      addRule: "+ Add Rule",
      additionalRulesHint: "Additional rules are checked before the default actions.",
      installProfile: "Install Profile",
      shareProfile: "Share Profile",
      shareStrongSwan: "Share strongSwan",
      localProcessingNote: "Profile data and imported files are processed locally in your browser. Nothing is sent to the server.",
      disclaimer: "TOLF Configurator is an independent project and is not affiliated with, endorsed by, sponsored by, or supported by Apple Inc. or Google LLC. Apple and Google are not responsible for this site or for configuration profiles generated by it. Apple, iPhone, iPad and iOS are trademarks of Apple Inc. Android and Google are trademarks of Google LLC."
    },
    ru: {
      rootTitle: "TOLF Configurator",
      backTolf: "‹ TOLF",
      rootSubtitle: "Создавайте сетевые конфигурации прямо в браузере.",
      ikev2Description: "Создавайте IKEv2-конфигурации для устройств Apple, Android strongSwan и Windows PowerShell (.ps1).",
      comingSoon: "Скоро",
      dnsDescription: "Создавайте системные конфигурации DNS.",
      wifiDescription: "Создавайте профили конфигурации Wi-Fi.",
      privacyVerification: "Конфиденциальность и проверка",
      ikev2Title: "IKEv2 — TOLF Configurator",
      backConfigurator: "‹ TOLF Configurator",
      ikev2Subtitle: "Создавайте конфигурации IKEv2 для устройств Apple, strongSwan на Android и Windows PowerShell.",
      importExistingConfiguration: "Импортировать конфигурацию",
      connection: "Подключение",
      name: "Название",
      server: "Сервер",
      remoteId: "Remote ID",
      localId: "Local ID",
      optional: "Необязательно",
      authentication: "Аутентификация",
      username: "Имя пользователя",
      password: "Пароль",
      advancedSettings: "Дополнительные настройки",
      ikeEncryption: "Шифрование IKE",
      ikeIntegrity: "Контроль целостности IKE",
      diffieHellman: "Diffie-Hellman",
      dpd: "Dead Peer Detection",
      appleOnly: "Только Apple",
      none: "Нет",
      low: "Low",
      medium: "Medium",
      high: "High",
      pfs: "Perfect Forward Secrecy",
      redirects: "Перенаправления",
      internalSubnet: "Атрибуты внутренней подсети IPv4/IPv6",
      onDemand: "On Demand",
      enableOnDemand: "Включить On Demand",
      alwaysOn: "Always On",
      alwaysOnHint: "Подключаться автоматически во всех сетях.",
      defaultActions: "Действия по умолчанию",
      wifi: "Wi-Fi",
      cellular: "Сотовая сеть",
      ethernet: "Ethernet",
      connect: "Подключить",
      disconnect: "Отключить",
      ignore: "Игнорировать",
      additionalRules: "Дополнительные правила",
      addRule: "+ Добавить правило",
      additionalRulesHint: "Дополнительные правила проверяются перед действиями по умолчанию.",
      installProfile: "Установить профиль",
      shareProfile: "Поделиться профилем",
      shareStrongSwan: "Поделиться strongSwan",
      localProcessingNote: "Данные профиля и импортированные файлы обрабатываются локально в браузере. На сервер ничего не отправляется.",
      disclaimer: "TOLF Configurator — независимый проект, не связанный с Apple Inc. или Google LLC и не поддерживаемый ими. Apple и Google не несут ответственности за этот сайт и создаваемые им конфигурационные профили. Apple, iPhone, iPad и iOS являются товарными знаками Apple Inc. Android и Google являются товарными знаками Google LLC."
    },
    lv: {
      rootTitle: "TOLF Configurator",
      backTolf: "‹ TOLF",
      rootSubtitle: "Izveidojiet tīkla konfigurācijas tieši pārlūkprogrammā.",
      ikev2Description: "Izveidojiet IKEv2 konfigurācijas Apple ierīcēm, Android strongSwan un Windows PowerShell (.ps1).",
      comingSoon: "Drīzumā",
      dnsDescription: "Izveidojiet sistēmas DNS konfigurācijas profilu.",
      wifiDescription: "Izveidojiet Wi-Fi konfigurācijas profilu.",
      privacyVerification: "Privātums un pārbaude",
      ikev2Title: "IKEv2 — TOLF Configurator",
      backConfigurator: "‹ TOLF Configurator",
      ikev2Subtitle: "Izveidojiet IKEv2 konfigurācijas Apple ierīcēm, strongSwan Android ierīcēs un Windows PowerShell.",
      importExistingConfiguration: "Importēt esošu konfigurāciju",
      connection: "Savienojums",
      name: "Nosaukums",
      server: "Serveris",
      remoteId: "Remote ID",
      localId: "Local ID",
      optional: "Neobligāti",
      authentication: "Autentifikācija",
      username: "Lietotājvārds",
      password: "Parole",
      advancedSettings: "Papildu iestatījumi",
      ikeEncryption: "IKE šifrēšana",
      ikeIntegrity: "IKE integritāte",
      diffieHellman: "Diffie-Hellman",
      dpd: "Dead Peer Detection",
      appleOnly: "Tikai Apple",
      none: "Nav",
      low: "Low",
      medium: "Medium",
      high: "High",
      pfs: "Perfect Forward Secrecy",
      redirects: "Pāradresācijas",
      internalSubnet: "IPv4/IPv6 iekšējā apakštīkla atribūti",
      onDemand: "On Demand",
      enableOnDemand: "Ieslēgt On Demand",
      alwaysOn: "Always On",
      alwaysOnHint: "Automātiski izveidot savienojumu visos tīklos.",
      defaultActions: "Noklusējuma darbības",
      wifi: "Wi-Fi",
      cellular: "Mobilais tīkls",
      ethernet: "Ethernet",
      connect: "Savienot",
      disconnect: "Atvienot",
      ignore: "Ignorēt",
      additionalRules: "Papildu noteikumi",
      addRule: "+ Pievienot noteikumu",
      additionalRulesHint: "Papildu noteikumi tiek pārbaudīti pirms noklusējuma darbībām.",
      installProfile: "Instalēt profilu",
      shareProfile: "Kopīgot profilu",
      shareStrongSwan: "Kopīgot strongSwan",
      localProcessingNote: "Profila dati un importētie faili tiek apstrādāti lokāli jūsu pārlūkprogrammā. Nekas netiek nosūtīts uz serveri.",
      disclaimer: "TOLF Configurator ir neatkarīgs projekts, kas nav saistīts ar Apple Inc. vai Google LLC un nav šo uzņēmumu atbalstīts. Apple un Google nav atbildīgi par šo vietni vai tās izveidotajiem konfigurācijas profiliem. Apple, iPhone, iPad un iOS ir Apple Inc. preču zīmes. Android un Google ir Google LLC preču zīmes."
    }
  };

  function applyLanguage(lang) {
    const dictionary = text[lang] || text.en;
    document.documentElement.lang = lang;
    localStorage.setItem("tolf-language", lang);

    document.querySelectorAll("[data-i18n]").forEach(element => {
      const key = element.dataset.i18n;
      if (Object.prototype.hasOwnProperty.call(dictionary, key)) {
        element.textContent = dictionary[key];
      }
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach(element => {
      const key = element.dataset.i18nPlaceholder;
      if (Object.prototype.hasOwnProperty.call(dictionary, key)) {
        element.placeholder = dictionary[key];
      }
    });

    document.querySelectorAll(".language button[data-lang]").forEach(button => {
      const active = button.dataset.lang === lang;
      button.classList.toggle("active", active);
      button.setAttribute("aria-pressed", active ? "true" : "false");
    });

    document.querySelectorAll("[data-lang-link]").forEach(link => {
      try {
        const target = new URL(link.getAttribute("href"), window.location.href);
        target.searchParams.set("lang", lang);
        link.href = target.href;
      } catch (_) {}
    });
  }

  document.querySelectorAll(".language button[data-lang]").forEach(button => {
    button.addEventListener("click", () => {
      const next = button.dataset.lang;
      if (!supported.includes(next) || next === document.documentElement.lang) {
        return;
      }

      localStorage.setItem("tolf-language", next);
      const target = new URL(window.location.href);
      target.searchParams.set("lang", next);
      window.location.href = target.href;
    });
  });

  applyLanguage(language);
})();
